version: "3.7"

services:
  web:
    build: .
    container_name: ${PROJECT_NAME}Web
    volumes:
      - ./:/app
      - staticfiles:/app/staticfiles
      - mediafiles:/app/media
    environment:
      DJANGO_ADMIN_USERNAME: admin@gmail.com
      DJANGO_ADMIN_PASSWORD: admin12345
      DJANGO_SETTINGS_FOLDER: core

  nginx:
    image: nginx
    container_name: ${PROJECT_NAME}Nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/app/static
      - mediafiles:/app/media
    depends_on:
      - web


volumes:
  staticfiles:
    name: ${PROJECT_NAME}Staticfiles

  mediafiles:
    name: ${PROJECT_NAME}Mediafiles