# Generated by Django 3.2.7 on 2021-09-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagesContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide', models.TextField()),
                ('what_is_boozecoin', models.TextField()),
                ('booz_it_up', models.TextField()),
                ('faq', models.TextField()),
            ],
            options={
                'verbose_name': 'Pages content',
            },
        ),
    ]
