# Generated by Django 3.2.7 on 2021-09-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_pagescontent_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagescontent',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pagescontent',
            name='booz_it_up',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pagescontent',
            name='faq',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pagescontent',
            name='guide',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pagescontent',
            name='what_is_boozecoin',
            field=models.TextField(default=''),
        ),
    ]
