# Generated by Django 3.2.7 on 2021-09-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_pagescontent_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagescontent',
            name='guide',
            field=models.TextField(default=''),
        ),
    ]
