# Generated by Django 3.2.7 on 2021-09-12 07:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_pagescontent_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagescontent',
            name='about',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='pagescontent',
            name='booz_it_up',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='pagescontent',
            name='faq',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='pagescontent',
            name='guide',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='pagescontent',
            name='what_is_boozecoin',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
